# vorn-mat reproducibility substrate
#
# Canonical Docker image for reproducing the family-wave canonical artifacts
# documented in the vorn-mat paper. The pin set below is a best-guess
# reconstruction from raw-report timestamps and PyPI release chronology — the
# original public runs did not preserve a lockfile or Modal image hash. See
# README.md "Reproducibility disclosure" for the full provenance read.
#
# Base: CUDA 12.4.1 + cuDNN runtime on Ubuntu 22.04. Matches the A100/H100
# driver expectations on Modal and is the smallest base that still ships the
# CUDA runtime needed by torch 2.12.

FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
        software-properties-common \
        ca-certificates \
        curl \
        git \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y --no-install-recommends \
        python3.11 \
        python3.11-venv \
        python3.11-dev \
        python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN ln -sf /usr/bin/python3.11 /usr/local/bin/python \
    && ln -sf /usr/bin/python3.11 /usr/local/bin/python3 \
    && python -m pip install --upgrade pip==25.0

WORKDIR /app

# Hash-locked transitive closure. Generated by:
#   uv pip compile --generate-hashes pyproject.toml --extra local -o requirements.lock
# Regenerate only when the pin set in pyproject.toml changes intentionally.
COPY requirements.lock /app/requirements.lock
RUN pip install --require-hashes -r /app/requirements.lock

# Install the vorn-mat package itself (source mounted by Modal at run time;
# this layer primes the editable install so test imports work in-container).
COPY pyproject.toml /app/pyproject.toml
COPY src /app/src
RUN pip install --no-deps -e /app

# Default working layout matches the Modal volume mount convention.
ENV VORN_MAT_VOLUME_PATH=/vol \
    VORN_MAT_MODEL_CACHE=/vol/models \
    VORN_MAT_RESULTS_ROOT=/vol/results/vorn-mat \
    VORN_MAT_BENCHMARK_CACHE=/vol/benchmarks
