"""Vorn-Mat: prototype implementation for the residual-direction KV-cache
eviction experiments reported in the vorn-mat paper.

This package implements:

- `vorn.py` — residual-direction scoring at the canonical mid-depth layer
  (`L* = L // 2`) under a prefill-time cache selection contract with full-
  prompt visibility.
- `live_eviction.py` — token-level and sentence-level retention policies for
  the vorn scoring signal, plus TOVA-style and H2O-style attention-weight
  baselines under the same one-shot prefill contract.
- `plan.py`, `runner.py`, `remote_exec.py` — experiment plan dataclasses,
  result-envelope JSON schemas, and Modal job dispatch.
- `paired_stats.py` — exact paired McNemar tests over per-fixture
  observations preserved in each result row.

See the companion paper for the family-conditional KV-cache eviction
finding and the granularity rescue-spectrum result this code was used to
produce. Released artifacts are in `results/`; the `scripts/` directory
includes the Appendix A recompute script and the cross-family statistics
script referenced in the paper.
"""

from .baselines import BASELINES, BaselineSpec, get_baseline
from .baselines.live_eviction import (
    H2O_ATTENTION_CONTRACT,
    LiveEvictionConfig,
    LiveEvictionPredictionTrace,
    LiveEvictionStats,
    LiveEvictionTextGenerator,
    SEMANTIC_SUMMARY_CONTRACT,
    SUMMARIZE_COMPACT_CONTRACT,
    TOVA_ATTENTION_CONTRACT,
    accumulate_attention_scores,
    extract_canonical_token_summaries,
    extract_last_token_attention_scores,
    run_live_eviction,
    select_attention_score_retained_positions,
    select_prefix_suffix_retained_positions,
    select_random_retained_positions,
    select_sliding_window_retained_positions,
    summary_fingerprint,
)
from .baselines.vanilla import PredictionTrace, TextGenerator, run_vanilla
from .baselines.vorn import (
    RetentionStats,
    VornPredictionTrace,
    VornRetentionConfig,
    VornTextGenerator,
    compute_vorn_direction,
    cosine_similarity,
    run_vorn,
    select_retained_positions,
)
from .benchmarks import (
    BENCHMARKS,
    BenchmarkSpec,
    benchmark_case_from_ruler_record,
    get_benchmark,
    load_cases,
    load_ruler_hf_niah_slice,
    score_predictions,
)
from .benchmarks.niah import (
    EVICTION_ANTAGONIST_FIXTURE,
    EVICTION_ANTAGONIST_SUITE_ID,
    load_eviction_antagonist_cases,
)
from .benchmarks.common import BenchmarkCase
from .local_exec import (
    LocalModelConfig,
    TransformersObservationGenerator,
    TransformersLiveEvictionGenerator,
    TransformersScoreDistributionObservationGenerator,
    TransformersTextGenerator,
    TransformersVornGenerator,
    build_summary_answer_prompt,
    build_summary_prompt,
    run_local_live_eviction_smoke,
    run_local_step1_pair,
    run_local_vanilla_smoke,
    select_live_eviction_plan,
    select_step1_plans,
    split_context_and_question_for_summary,
    select_week1_plan,
)
from .modal_app import (
    ModalAppSpec,
    ModalArtifacts,
    ModalBinding,
    build_modal_artifacts,
    build_vanilla_entrypoint,
    build_vorn_entrypoint,
    default_modal_app_spec,
)
from .neighborhood_probe import (
    NeighborhoodSpan,
    analyze_neighborhood_probes,
    build_standard_neighborhoods,
    expand_token_span,
    line_char_span,
    paragraph_char_span,
    sentence_char_span,
    token_span_from_offsets,
    write_neighborhood_probe_artifacts,
)
from .observation import (
    ObservationCase,
    ObservationReport,
    ObservationStep,
    ObservationTopPosition,
    analyze_observation_report,
    answer_token_indices,
    find_subsequence_spans,
    jaccard_similarity,
    load_observation_report,
    residual_l2_norms,
    round_float_list,
    select_top_alignment_positions,
    write_observation_artifacts,
)
from .plan import (
    A100_80GB_PER_SECOND,
    DEFAULT_CANONICAL_LAYER,
    DEFAULT_LIVE_EVICTION_CACHE_BUDGET,
    DEFAULT_LIVE_EVICTION_CASE_LIMIT,
    DEFAULT_MODEL,
    DEFAULT_RANDOM_LIVE_EVICTION_SEED,
    DEFAULT_RECENT_WINDOW,
    DEFAULT_STEP1_CACHE_BUDGET,
    DEFAULT_STEP1_CASE_LIMIT,
    ExperimentDefaults,
    LiveEvictionDefaults,
    Step1Defaults,
    Week1Run,
    build_live_eviction_run,
    build_step1_run_matrix,
    build_week1_run_matrix,
    estimate_week1_cost_window,
    middle_layer_index,
    per_hour_rate,
)
from .async_dispatch import (
    WaveStateFile,
    collect_wave_results,
    dispatch_wave_async,
)
from .orchestration import (
    CellFailure,
    CellWaveReport,
    collect_cells_parallel,
    run_wave_serialized,
    serialize_cell_wave_report,
)
from .progress import (
    ProgressLogger,
    default_progress_logger,
    format_case_progress,
    format_complete,
    format_dataset_loaded,
)
from .results import (
    CaseObservation,
    RunResult,
    append_observation,
    append_result,
    load_observations,
    load_results,
    observations_path,
)
from .runner import ExecutionPlan, build_execution_plans
from .remote_exec import (
    ModalLiveEvictionRunReport,
    ModalLiveEvictionRunRequest,
    ModalScoreDistributionObservationRequest,
    ModalVanillaObservationRequest,
    ModalVanillaRunReport,
    ModalVanillaRunRequest,
    run_modal_live_eviction_niah,
    run_modal_score_distribution_observation_niah,
    run_modal_vanilla_observation_niah,
    run_modal_vanilla_niah,
)
from .score_distribution_observation import (
    ScoreDistributionObservationCase,
    ScoreDistributionObservationReport,
    ScoreDistributionStats,
    ScoreDistributionObservationStep,
    adjacency_fraction,
    score_distribution_stats,
    write_score_distribution_observation_report,
)

__all__ = [
    "A100_80GB_PER_SECOND",
    "BASELINES",
    "BENCHMARKS",
    "BaselineSpec",
    "BenchmarkCase",
    "BenchmarkSpec",
    "CaseObservation",
    "CellFailure",
    "CellWaveReport",
    "EVICTION_ANTAGONIST_FIXTURE",
    "EVICTION_ANTAGONIST_SUITE_ID",
    "ModalLiveEvictionRunReport",
    "ModalLiveEvictionRunRequest",
    "ModalScoreDistributionObservationRequest",
    "ModalVanillaRunReport",
    "ModalVanillaRunRequest",
    "DEFAULT_CANONICAL_LAYER",
    "DEFAULT_LIVE_EVICTION_CACHE_BUDGET",
    "DEFAULT_LIVE_EVICTION_CASE_LIMIT",
    "DEFAULT_MODEL",
    "DEFAULT_RANDOM_LIVE_EVICTION_SEED",
    "DEFAULT_RECENT_WINDOW",
    "DEFAULT_STEP1_CACHE_BUDGET",
    "DEFAULT_STEP1_CASE_LIMIT",
    "ExperimentDefaults",
    "ExecutionPlan",
    "extract_canonical_token_summaries",
    "extract_last_token_attention_scores",
    "LocalModelConfig",
    "LiveEvictionConfig",
    "LiveEvictionDefaults",
    "LiveEvictionPredictionTrace",
    "LiveEvictionStats",
    "LiveEvictionTextGenerator",
    "ModalAppSpec",
    "ModalArtifacts",
    "ModalBinding",
    "PredictionTrace",
    "ProgressLogger",
    "RetentionStats",
    "RunResult",
    "ModalVanillaObservationRequest",
    "NeighborhoodSpan",
    "ObservationCase",
    "ObservationReport",
    "ObservationStep",
    "ObservationTopPosition",
    "ScoreDistributionObservationCase",
    "ScoreDistributionObservationReport",
    "ScoreDistributionObservationStep",
    "ScoreDistributionStats",
    "H2O_ATTENTION_CONTRACT",
    "SEMANTIC_SUMMARY_CONTRACT",
    "SUMMARIZE_COMPACT_CONTRACT",
    "Step1Defaults",
    "TOVA_ATTENTION_CONTRACT",
    "TextGenerator",
    "TransformersLiveEvictionGenerator",
    "TransformersObservationGenerator",
    "TransformersScoreDistributionObservationGenerator",
    "TransformersVornGenerator",
    "VornPredictionTrace",
    "VornRetentionConfig",
    "VornTextGenerator",
    "Week1Run",
    "append_observation",
    "append_result",
    "benchmark_case_from_ruler_record",
    "WaveStateFile",
    "collect_cells_parallel",
    "collect_wave_results",
    "dispatch_wave_async",
    "run_wave_serialized",
    "serialize_cell_wave_report",
    "build_execution_plans",
    "build_live_eviction_run",
    "build_step1_run_matrix",
    "build_week1_run_matrix",
    "build_modal_artifacts",
    "build_summary_answer_prompt",
    "build_summary_prompt",
    "build_vanilla_entrypoint",
    "build_vorn_entrypoint",
    "build_standard_neighborhoods",
    "accumulate_attention_scores",
    "analyze_observation_report",
    "analyze_neighborhood_probes",
    "answer_token_indices",
    "compute_vorn_direction",
    "cosine_similarity",
    "default_modal_app_spec",
    "default_progress_logger",
    "format_case_progress",
    "format_complete",
    "format_dataset_loaded",
    "estimate_week1_cost_window",
    "expand_token_span",
    "find_subsequence_spans",
    "get_baseline",
    "get_benchmark",
    "jaccard_similarity",
    "line_char_span",
    "load_cases",
    "load_observation_report",
    "load_observations",
    "load_eviction_antagonist_cases",
    "load_ruler_hf_niah_slice",
    "load_results",
    "observations_path",
    "middle_layer_index",
    "paragraph_char_span",
    "residual_l2_norms",
    "run_live_eviction",
    "run_local_live_eviction_smoke",
    "run_local_step1_pair",
    "run_modal_live_eviction_niah",
    "run_modal_score_distribution_observation_niah",
    "run_modal_vanilla_observation_niah",
    "run_modal_vanilla_niah",
    "per_hour_rate",
    "round_float_list",
    "run_vorn",
    "run_local_vanilla_smoke",
    "run_vanilla",
    "score_predictions",
    "select_attention_score_retained_positions",
    "select_prefix_suffix_retained_positions",
    "select_random_retained_positions",
    "select_retained_positions",
    "select_sliding_window_retained_positions",
    "select_live_eviction_plan",
    "select_top_alignment_positions",
    "select_step1_plans",
    "select_week1_plan",
    "sentence_char_span",
    "score_distribution_stats",
    "split_context_and_question_for_summary",
    "summary_fingerprint",
    "token_span_from_offsets",
    "TransformersTextGenerator",
    "adjacency_fraction",
    "write_neighborhood_probe_artifacts",
    "write_observation_artifacts",
    "write_score_distribution_observation_report",
]
